"""Добавление полей в bouquet2

Revision ID: 63831423959d
Revises: 95bf8a30f44d
Create Date: 2024-02-13 21:31:07.511449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63831423959d'
down_revision = '95bf8a30f44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquet', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
