"""Добавление полей в bouquet

Revision ID: 95bf8a30f44d
Revises: 
Create Date: 2024-02-13 17:06:42.600696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bf8a30f44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['sku'])

    with op.batch_alter_table('bouquet_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    with op.batch_alter_table('bouquet_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bouquet_materials', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('bouquet_material', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('bouquet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('active')
        batch_op.drop_column('category')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
