version: '3.7'
services:
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - warehouse_net

  web:
    build: .
    command: python main.py --host=0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - warehouse_net
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: shelomitsky2011@yandex.by
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin     
    ports:
      - "5050:80"
    networks:
      - warehouse_net
    depends_on:
      - db
    user: "pgadmin"

networks:
  warehouse_net:
    external: true
    driver: bridge

volumes:
  db:
  pgadmin: