version: '3.7'
services:
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - warehouse_net

  web:
    build: .
    command: python main.py --host=0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - warehouse_net
    depends_on:
      - db

networks:
  warehouse_net:
    external: true
    driver: bridge

volumes:
  db: