version: '3.7'
services:
  dwhdb:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - warehouse_net

  web:
    build: .
    command: python main.py --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - warehouse_net
    depends_on:
      - dwhdb
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: shelomitsky2011@yandex.by
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_LANGUAGE: ru_RU
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      POSTGRES_HOST: dwhdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin     
    ports:
      - "5050:80"
    networks:
      - warehouse_net
    depends_on:
      - dwhdb
    user: "pgadmin"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiZGM5MTQ4OGZjMDk1NjYxYzFhYzhiMDAwZTZlMTk4ZmUiLCJ0IjoiYzE4YjUxOGQtN2FlYy00ZDAxLWE2ZDAtOTE0ZWE3YjBjZWRmIiwicyI6Ik1UVTNaVGt4WlRZdE16WTRaQzAwWWpNNUxXSmxNVEl0TURWaFltTTJaREU1Wm1VMyJ9

    networks:
      - warehouse_net

networks:
  warehouse_net:
    external: true
    driver: bridge

volumes:
  db:
  pgadmin: